//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Home_Library
{
    using System;
    using System.Collections.Generic;
    
    public partial class BIBKA_Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BIBKA_Book()
        {
            this.BIBKA_Book_Author = new HashSet<BIBKA_Book_Author>();
            this.BIBKA_Book_Genre = new HashSet<BIBKA_Book_Genre>();
            this.BIBKA_Book_Izdatel = new HashSet<BIBKA_Book_Izdatel>();
            this.BIBKA_History = new HashSet<BIBKA_History>();
        }
    
        public int id_book { get; set; }
        public string book_name { get; set; }
        public string book_description { get; set; }
        public string book_photo { get; set; }
        public Nullable<int> book_produce_year { get; set; }
        public Nullable<int> book_amount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BIBKA_Book_Author> BIBKA_Book_Author { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BIBKA_Book_Genre> BIBKA_Book_Genre { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BIBKA_Book_Izdatel> BIBKA_Book_Izdatel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BIBKA_History> BIBKA_History { get; set; }
    }
}
