//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Home_Library
{
    using System;
    using System.Collections.Generic;
    
    public partial class BIBKA_History
    {
        public int id_history { get; set; }
        public Nullable<int> fk_id_user { get; set; }
        public Nullable<int> fk_id_book { get; set; }
        public Nullable<int> fk_id_status { get; set; }
    
        public virtual BIBKA_Book BIBKA_Book { get; set; }
        public virtual BIBKA_Status BIBKA_Status { get; set; }
        public virtual BIBKA_User BIBKA_User { get; set; }
    }
}
