//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Home_Library
{
    using System;
    using System.Collections.Generic;
    
    public partial class BIBKA_Book_Author
    {
        public int id_book_author { get; set; }
        public Nullable<int> fk_id_book { get; set; }
        public Nullable<int> fk_id_author { get; set; }
    
        public virtual BIBKA_Author BIBKA_Author { get; set; }
        public virtual BIBKA_Book BIBKA_Book { get; set; }
    }
}
