//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Home_Library
{
    using System;
    using System.Collections.Generic;
    
    public partial class BIBKA_Izdatel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BIBKA_Izdatel()
        {
            this.BIBKA_Book_Izdatel = new HashSet<BIBKA_Book_Izdatel>();
        }
    
        public int id_izdatel { get; set; }
        public string izdatel_name { get; set; }
        public string izdatel_adress { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BIBKA_Book_Izdatel> BIBKA_Book_Izdatel { get; set; }
    }
}
