//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Home_Library
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BIBKA_Author> BIBKA_Author { get; set; }
        public virtual DbSet<BIBKA_Book> BIBKA_Book { get; set; }
        public virtual DbSet<BIBKA_Book_Author> BIBKA_Book_Author { get; set; }
        public virtual DbSet<BIBKA_Book_Genre> BIBKA_Book_Genre { get; set; }
        public virtual DbSet<BIBKA_Book_Izdatel> BIBKA_Book_Izdatel { get; set; }
        public virtual DbSet<BIBKA_Genre> BIBKA_Genre { get; set; }
        public virtual DbSet<BIBKA_History> BIBKA_History { get; set; }
        public virtual DbSet<BIBKA_Izdatel> BIBKA_Izdatel { get; set; }
        public virtual DbSet<BIBKA_Role> BIBKA_Role { get; set; }
        public virtual DbSet<BIBKA_Status> BIBKA_Status { get; set; }
        public virtual DbSet<BIBKA_User> BIBKA_User { get; set; }
    }
}
